// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxBlmWVbdxP-F4qSiU_x7SAi7T6vftiEg',
    appId: '1:113827941836:web:4205e56032f53726266169',
    messagingSenderId: '113827941836',
    projectId: 'flutter-reddit-clone-f91d2',
    authDomain: 'flutter-reddit-clone-f91d2.firebaseapp.com',
    storageBucket: 'flutter-reddit-clone-f91d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLIWoxtv6buwJAqIJUkXxE9rAdwgZfN-I',
    appId: '1:113827941836:android:56d18fe6e8f62db9266169',
    messagingSenderId: '113827941836',
    projectId: 'flutter-reddit-clone-f91d2',
    storageBucket: 'flutter-reddit-clone-f91d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3TsRpjsULXLrdGTjN2-Vpevjdj5kn3UQ',
    appId: '1:113827941836:ios:194e2c15027b4233266169',
    messagingSenderId: '113827941836',
    projectId: 'flutter-reddit-clone-f91d2',
    storageBucket: 'flutter-reddit-clone-f91d2.appspot.com',
    iosClientId: '113827941836-g8q6q9pdupbr4hqs2t4d80kfl6ao9j4h.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
